name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'feat:'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'fix:'
    labels:
      - 'bug'
  - title: 'patch:'
    labels:
      - 'dependencies'
exclude-labels:
  - 'invalid'
  - 'duplicate'
  - 'wontfix'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'enhancement'
      - 'bug'
      - 'minor'
  patch:
    labels:
      - 'dependencies'
      - 'patch'
      - 'github-action'
  default: patch
change-template: '- #$NUMBER $TITLE (@$AUTHOR)'
template: |
  $CHANGES

  Contributors:
  $CONTRIBUTORS

  Previous Tag:
  [$PREVIOUS_TAG](https://github.com/AdamJ/task-it/releases/tag/$PREVIOUS_TAG)

  [All Tags](https://github.com/AdamJ/task-it/tags)
  [All Releases](https://github.com/AdamJ/task-it/releases)
no-changes-template: |
  Nothing to see here...
