name: Site Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Setup Node.js
      uses: actions/setup-node@v4.2.0
      with:
        node-version: '22'
        registry-url: 'https://registry.npmjs.org'

    - name: Authenticate with npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./dist
        publish_branch: gh-pages
        commit_message: ${{ github.event.head_commit.message }}
