name: Site Build

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'
          env:
            NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKENS}}
        - name: Install dependencies using a safe clean install, build and test
          run: |
            npm ci --ignore-scripts
        - name: Run Build
          run: npm run build
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3.9.3
          with:
            deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
            publish_dir: ./dist
            publish_branch: gh-pages
            commit_message: ${{ github.event.head_commit.message }}
